"""The capture wrapper — shooting a screen in the rasteriser it ships in.

Method rules encoded here
-------------------------
* **Rule 1 — measure in the SHIPPING rasteriser.** ``capture-ios.mjs`` launches
  with ``--font-render-hinting=none``. A bare ``chromium.launch()`` hints stems
  to whole pixels and shifts advances; that alone produced a false +5 px advance
  defect on 001 and explained an entire grader-versus-builder disagreement.
* **The phone context is 393x852 pt at deviceScaleFactor 2.170483**, so one
  output pixel is one canonical device pixel and the file lands 853 wide.
  ``isMobile: false`` with ``hasTouch: true`` is deliberate and
  counter-intuitive: Chromium's ``isMobile: true`` is Android wide-viewport
  mode, which widens the layout viewport to content width (innerWidth 1450 on
  /signin), makes ``window.scrollTo`` inert and puts controls outside the visual
  viewport. iOS WKWebView does not do that. Screenshots under both settings were
  verified pixel-identical where both work.
* **Park the mouse and kill the caret before every shot.** A stray hover once
  baked a false "highlighted row" defect into a screenshot, and a blinking caret
  is a nondeterministic pixel.
* **Rule 17 — ask what STATE canonical is in before measuring a single band.**
  Canonical 003 is not an empty sign-in form: it shows a typed address, a
  16-character password masked to 16 bullets, a green validation ring and two
  "Looks good." lines, none of which exist until the player types. Measuring it
  against a default render compares two different screens. Reach the state the
  way a player reaches it — :func:`capture_variants` takes ``fill`` and ``blur``
  steps for exactly this. **Check every form screen for the same thing.**
* **The desktop guard uses a BARE launch.** ``capture-web.mjs`` passes no flags
  and every desktop grade on record was made in that rasteriser. Using
  ``--font-render-hinting=none`` there shifts text and swamps the diff. The two
  harnesses genuinely disagree, so never compare across them —
  :func:`desktop_launch_args` exists to make that explicit rather than
  accidental.

Nothing here modifies ``capture-ios.mjs``; :func:`capture_ios` shells out to it.
:func:`capture_variants` is the other half — N parameter sets rendered from ONE
page load, which is what makes a solver loop affordable.
"""

import json
import os
import shutil
import subprocess
import tempfile

from .errors import MeasurementError

#: 393 x 852 CSS pt. Canonical PNGs are 853 x 1844 because the canonical
#: artboard is 850 pt tall; see :mod:`measure.compare`.
PHONE_VIEWPORT = {"width": 393, "height": 852}
DEVICE_SCALE_FACTOR = 2.170483
PHONE_CONTEXT = {
    "viewport": PHONE_VIEWPORT,
    "deviceScaleFactor": DEVICE_SCALE_FACTOR,
    "isMobile": False,
    "hasTouch": True,
}
#: Rule 1. Do not drop this flag, and do not add it to a desktop capture.
IOS_LAUNCH_ARGS = ["--font-render-hinting=none"]

HERE = os.path.dirname(os.path.abspath(__file__))
#: The shipping harness. Imported and wrapped, never edited.
CAPTURE_IOS = os.path.join(os.path.dirname(HERE), "capture-ios.mjs")

_NO_CARET = (
    "*, *::before, *::after { caret-color: transparent !important; }"
)

_VARIANTS_JS = r"""
/* GENERATED by measure/capture.py — do not commit. One page load, N parameter
   sets, N screenshots. Same launch args and context as capture-ios.mjs. */
import { chromium } from 'playwright'
import fs from 'fs'

const SPEC = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'))
const NO_CARET = %(no_caret)s

const b = await chromium.launch({ args: SPEC.launchArgs })
const ctx = await b.newContext(SPEC.context)
await ctx.addInitScript((css) => {
  const inject = () => {
    const s = document.createElement('style')
    s.setAttribute('data-harness', 'no-caret')
    s.textContent = css
    document.head.appendChild(s)
  }
  if (document.head) inject()
  else document.addEventListener('DOMContentLoaded', inject, { once: true })
}, NO_CARET)

const p = await ctx.newPage()
await p.mouse.move(2, 2)
await p.goto(SPEC.url, { waitUntil: 'domcontentloaded' })
await p.waitForTimeout(SPEC.settle)

/* Rule 17: reach the state canonical is in, the way a player reaches it. */
for (const step of SPEC.steps || []) {
  if (step.action === 'fill') {
    await p.locator(step.selector).filter({ visible: true }).first().fill(step.value, { timeout: 8000 })
  } else if (step.action === 'click') {
    await p.locator(step.selector).filter({ visible: true }).first().click({ timeout: 8000 })
  } else if (step.action === 'blur') {
    await p.evaluate(() => { const el = document.activeElement; if (el instanceof HTMLElement) el.blur() })
  } else {
    throw new Error('unknown step action ' + step.action)
  }
  await p.waitForTimeout(step.wait || 600)
}

await p.evaluate(() => {
  const el = document.createElement('style')
  el.id = 'measure-variant'
  document.body.appendChild(el)
})

for (const v of SPEC.variants) {
  await p.evaluate(([css, mq]) => {
    document.getElementById('measure-variant').textContent = mq ? mq + '{' + css + '}' : css
  }, [v.css || '', SPEC.mediaQuery || ''])
  await p.waitForTimeout(SPEC.repaint)
  await p.mouse.move(2, 2)
  await p.evaluate(() => window.scrollTo(0, 0))
  await p.screenshot({ path: v.out })
}
await b.close()
console.log(JSON.stringify({ shot: SPEC.variants.map((v) => v.out) }))
""" % {"no_caret": json.dumps(_NO_CARET)}


def desktop_launch_args():
    """Launch args for a DESKTOP capture: none. Deliberately a function.

    ESTIMATOR: not a measurement — a guard. Every desktop grade on record was
    made under a bare ``chromium.launch()``. Adding ``--font-render-hinting=none``
    there (correct for iOS) shifts text and swamps the diff, so the two
    harnesses genuinely disagree and a capture from one must never be compared
    to a capture from the other.
    """
    return []


def capture_ios(out_dir, scratch_dir, only=None, port=3181, app_dir=None, settle=2600,
                harness=CAPTURE_IOS, env=None, check=True):
    """Run the shipping iOS harness for one screen, or all 72. Rule 1.

    Wraps ``docs/shotiq/capture-ios.mjs`` unchanged, so the capture that gets
    measured is byte-for-byte the capture that gets graded. ``only='003'`` (or
    ``'003,004'``) shoots just those screens; the harness's duplicate and gap
    checks still run, still hard-fail, and still say that a filtered run proves
    nothing about the screens it did not shoot.

    Returns the completed :class:`subprocess.CompletedProcess`. Raises
    :class:`MeasurementError` if node or the harness is missing — the two
    failures that otherwise look like "the screen did not render".
    """
    if shutil.which("node") is None:
        raise MeasurementError("node is not on PATH; the capture harness is a Playwright script")
    if not os.path.exists(harness):
        raise MeasurementError(f"capture harness not found at {harness}")
    e = dict(os.environ)
    e.update({"S": str(scratch_dir), "OUT": str(out_dir), "PORT": str(port), "SETTLE": str(settle)})
    if app_dir:
        e["APP"] = str(app_dir)
    if only:
        e["ONLY"] = only if isinstance(only, str) else ",".join(only)
    if env:
        e.update({k: str(v) for k, v in env.items()})
    return subprocess.run(
        ["node", harness], env=e, check=check, capture_output=True, text=True,
        cwd=os.path.dirname(harness),
    )


def capture_variants(url, variants, out_dir, steps=(), media_query="@media (max-width: 767.98px)",
                     settle=2400, repaint=240, context=None, launch_args=None, keep_script=False):
    """Render N CSS parameter sets from ONE page load. The solver's inner loop.

    ``variants`` is ``{name: css}`` or a sequence of ``(name, css)``; each is
    injected into a single ``<style>`` element, wrapped in ``media_query`` when
    given, and screenshot to ``out_dir/<name>.png``. One page load for the whole
    sweep instead of one per parameter set — on 003 that is the difference
    between a four-cut display solve taking a minute and taking twenty.

    ``steps`` are rule-17 state steps in the harness's own vocabulary:
    ``{'action': 'fill', 'selector': ..., 'value': ...}``, ``'click'``,
    ``'blur'``. Capture the state canonical is in, or you are comparing two
    different screens.

    ``media_query`` defaults to the phone breakpoint because **rule 16**: a
    media query scopes CSS but does NOT scope an SVG attribute. Two ink
    corrections on 003 were made as markup attributes on shared components and
    painted at every viewport. Route a correction through the query — set
    ``fill`` on the path from inside it, and for a stroke keep
    ``stroke="<colour>"`` permanently with ``stroke-width="0"`` in the markup
    and raise the width only inside the query; a zero-width stroke paints
    nothing.

    Returns the list of PNG paths, in the order given.
    """
    if shutil.which("node") is None:
        raise MeasurementError("node is not on PATH; capture_variants drives Playwright")
    items = list(variants.items()) if isinstance(variants, dict) else list(variants)
    if not items:
        raise MeasurementError("capture_variants() got no variants — nothing to shoot")
    os.makedirs(out_dir, exist_ok=True)
    spec = {
        "url": url,
        "settle": settle,
        "repaint": repaint,
        "mediaQuery": media_query,
        "steps": list(steps),
        "context": context or PHONE_CONTEXT,
        "launchArgs": list(IOS_LAUNCH_ARGS if launch_args is None else launch_args),
        "variants": [{"name": n, "css": c, "out": os.path.join(out_dir, f"{n}.png")} for n, c in items],
    }
    tmp = tempfile.mkdtemp(prefix="measure-capture-")
    script = os.path.join(tmp, "variants.mjs")
    specfile = os.path.join(tmp, "spec.json")
    with open(script, "w") as f:
        f.write(_VARIANTS_JS)
    with open(specfile, "w") as f:
        json.dump(spec, f)
    try:
        subprocess.run(["node", script, specfile], check=True, capture_output=True, text=True,
                       cwd=os.path.dirname(CAPTURE_IOS))
    finally:
        if not keep_script:
            shutil.rmtree(tmp, ignore_errors=True)
    return [v["out"] for v in spec["variants"]]


def phone_context_js():
    """The context and launch block as JS source, for a one-off script.

    ESTIMATOR: not a measurement. Returns a string you can paste into a
    Playwright script so a throwaway probe still shoots in the shipping
    rasteriser at the shipping scale. If you find yourself writing
    ``chromium.launch()`` bare for a phone screen, that is rule 1 about to
    happen again.
    """
    return (
        "const b = await chromium.launch({ args: %s })\n"
        "const ctx = await b.newContext(%s)\n"
        "await ctx.addInitScript(() => {\n"
        "  const s = document.createElement('style')\n"
        "  s.textContent = %s\n"
        "  ;(document.head || document.documentElement).appendChild(s)\n"
        "})\n"
        "// before every screenshot: await p.mouse.move(2, 2)\n"
        % (json.dumps(IOS_LAUNCH_ARGS), json.dumps(PHONE_CONTEXT), json.dumps(_NO_CARET))
    )
