# Google Cloud Build configuration
# This file automates the build and deployment process

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/basketball-pose-detection'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'
    timeout: '1200s'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/basketball-pose-detection'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'basketball-pose-detection'
      - '--image'
      - 'gcr.io/$PROJECT_ID/basketball-pose-detection'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

images:
  - 'gcr.io/$PROJECT_ID/basketball-pose-detection'

options:
  machineType: 'N1_HIGHCPU_8'
  timeout: '1800s'
