// Canonical screen registry: route name -> component, one entry per canonical
// iOS screen (001-072). The structural check and the navigator both consume
// this, so a missing screen fails verification rather than silently 404ing.
import type { ComponentType } from 'react'
import {
  SplashScreen, WelcomeScreen, SignInScreen, CreateAccountScreen, VerifyEmailScreen,
  ForgotPasswordScreen, ResetPasswordScreen,
} from './screens/AuthFlow'
import {
  OnboardingIntroScreen, PhysicalProfileScreen, ExperienceBodyTypeScreen, ShootingProfileScreen,
  PlayerBioScreen, OnboardingReviewScreen, CameraPermissionPrimerScreen, PhotoLibraryPermissionScreen,
  NotificationPermissionPrimerScreen,
} from './screens/OnboardingFlow'
import {
  HomeScreen, AnalyzeHubScreen, PhotoUploadSourceScreen, PhotoReviewCropScreen,
  UploadQualityCheckScreen, UploadQueueScreen, VideoUploadScreen, VideoReviewScreen,
  LiveCameraSetupScreen, HoopCalibrationScreen, ReadinessCheckScreen, CaptureReadyScreen,
  LiveRecordingScreen, LiveFormFeedbackScreen, ShotDetectedScreen, CaptureReviewScreen,
} from './screens/HomeCaptureFlow'
import {
  AnalysisProcessingScreen, AnalysisTakingLongerScreen, AnalysisResultOverviewScreen,
  NoAnalysisYetScreen, AnalysisErrorScreen, ShotBreakdownScreen, FrameDetailSkeletonScreen,
  AnnotationToolbarScreen, FormScoreScreen, MetricDetailScreen, FlawsOverviewScreen, FlawDetailScreen,
  PlayerCardScreen, CustomizePlayerCardScreen, EliteMatchScreen, PhotoComparisonScreen,
  EliteShootersScreen, EliteShooterDetailScreen,
} from './screens/AnalysisEliteFlow'
import {
  TrainingHomeScreen, QuickStartScreen, DiscoverDrillsScreen, DrillDetailScreen, MyDrillsScreen,
  WorkoutCalendarScreen, DrillExecutionScreen, ShotTrackerScreen, WorkoutCompletionScreen,
  GoalsScreen, CreateGoalScreen, GoalDetailScreen, AnalyticsCardsScreen, AnalyticsDetailedScreen,
  MyMediaScreen, MediaDetailScreen, ProfileScreen, SettingsHubScreen, ShareResultsScreen,
} from './screens/TrainingMiscFlow'

/** route name -> [canonical screenId, component] */
export const SCREENS: Record<string, [string, ComponentType<any>]> = {
  Splash: ['ios.splash', SplashScreen],
  Welcome: ['ios.welcome', WelcomeScreen],
  SignIn: ['ios.sign-in', SignInScreen],
  CreateAccount: ['ios.create-account', CreateAccountScreen],
  VerifyEmail: ['ios.verify-email', VerifyEmailScreen],
  ForgotPassword: ['ios.forgot-password', ForgotPasswordScreen],
  ResetPassword: ['ios.reset-password', ResetPasswordScreen],
  OnboardingIntro: ['ios.onboarding-intro', OnboardingIntroScreen],
  PhysicalProfile: ['ios.physical-profile', PhysicalProfileScreen],
  ExperienceBodyType: ['ios.experience-body-type', ExperienceBodyTypeScreen],
  ShootingProfile: ['ios.shooting-profile', ShootingProfileScreen],
  PlayerBio: ['ios.player-bio', PlayerBioScreen],
  OnboardingReview: ['ios.onboarding-review', OnboardingReviewScreen],
  CameraPermissionPrimer: ['ios.camera-permission-primer', CameraPermissionPrimerScreen],
  PhotoLibraryPermission: ['ios.photo-library-permission', PhotoLibraryPermissionScreen],
  NotificationPermissionPrimer: ['ios.notification-permission-primer', NotificationPermissionPrimerScreen],
  HomeNewPlayer: ['ios.home-new-player', HomeScreen],
  HomeStandard: ['ios.home-standard', HomeScreen],
  HomeProfessional: ['ios.home-professional', HomeScreen],
  ProfileMenu: ['ios.profile-menu', HomeScreen],
  AnalyzeHub: ['ios.analyze-hub', AnalyzeHubScreen],
  PhotoUploadSource: ['ios.photo-upload-source', PhotoUploadSourceScreen],
  PhotoReviewCrop: ['ios.photo-review-crop', PhotoReviewCropScreen],
  UploadQualityCheck: ['ios.upload-quality-check', UploadQualityCheckScreen],
  UploadQueue: ['ios.upload-queue', UploadQueueScreen],
  VideoUpload: ['ios.video-upload', VideoUploadScreen],
  VideoReview: ['ios.video-review', VideoReviewScreen],
  LiveCameraSetup: ['ios.live-camera-setup', LiveCameraSetupScreen],
  HoopCalibration: ['ios.hoop-calibration', HoopCalibrationScreen],
  ReadinessCheck: ['ios.readiness-check', ReadinessCheckScreen],
  CaptureReady: ['ios.capture-ready', CaptureReadyScreen],
  LiveRecording: ['ios.live-recording', LiveRecordingScreen],
  LiveFormFeedback: ['ios.live-form-feedback', LiveFormFeedbackScreen],
  ShotDetected: ['ios.shot-detected', ShotDetectedScreen],
  CaptureReview: ['ios.capture-review', CaptureReviewScreen],
  AnalysisProcessing: ['ios.analysis-processing', AnalysisProcessingScreen],
  AnalysisTakingLonger: ['ios.analysis-taking-longer', AnalysisTakingLongerScreen],
  AnalysisResultOverview: ['ios.analysis-result-overview', AnalysisResultOverviewScreen],
  NoAnalysisYet: ['ios.no-analysis-yet', NoAnalysisYetScreen],
  AnalysisError: ['ios.analysis-error', AnalysisErrorScreen],
  ShotBreakdown: ['ios.shot-breakdown', ShotBreakdownScreen],
  FrameDetailSkeleton: ['ios.frame-detail-skeleton', FrameDetailSkeletonScreen],
  AnnotationToolbar: ['ios.annotation-toolbar', AnnotationToolbarScreen],
  FormScore: ['ios.form-score', FormScoreScreen],
  MetricDetail: ['ios.metric-detail', MetricDetailScreen],
  FlawsOverview: ['ios.flaws-overview', FlawsOverviewScreen],
  FlawDetail: ['ios.flaw-detail', FlawDetailScreen],
  PlayerCard: ['ios.player-card', PlayerCardScreen],
  CustomizePlayerCard: ['ios.customize-player-card', CustomizePlayerCardScreen],
  EliteMatch: ['ios.elite-match', EliteMatchScreen],
  PhotoComparison: ['ios.photo-comparison', PhotoComparisonScreen],
  EliteShooters: ['ios.elite-shooters', EliteShootersScreen],
  EliteShooterDetail: ['ios.elite-shooter-detail', EliteShooterDetailScreen],
  TrainingHome: ['ios.training-home', TrainingHomeScreen],
  QuickStart: ['ios.quick-start', QuickStartScreen],
  DiscoverDrills: ['ios.discover-drills', DiscoverDrillsScreen],
  DrillDetail: ['ios.drill-detail', DrillDetailScreen],
  MyDrills: ['ios.my-drills', MyDrillsScreen],
  WorkoutCalendar: ['ios.workout-calendar', WorkoutCalendarScreen],
  DrillExecution: ['ios.drill-execution', DrillExecutionScreen],
  ShotTracker: ['ios.shot-tracker', ShotTrackerScreen],
  WorkoutCompletion: ['ios.workout-completion', WorkoutCompletionScreen],
  Goals: ['ios.goals', GoalsScreen],
  CreateGoal: ['ios.create-goal', CreateGoalScreen],
  GoalDetail: ['ios.goal-detail', GoalDetailScreen],
  AnalyticsCards: ['ios.analytics-cards', AnalyticsCardsScreen],
  AnalyticsDetailed: ['ios.analytics-detailed', AnalyticsDetailedScreen],
  MyMedia: ['ios.my-media', MyMediaScreen],
  MediaDetail: ['ios.media-detail', MediaDetailScreen],
  Profile: ['ios.profile', ProfileScreen],
  SettingsHub: ['ios.settings-hub', SettingsHubScreen],
  ShareResults: ['ios.share-results', ShareResultsScreen],
}
